name: Auto tests

on: 
    workflow_dispatch:
        inputs:
            deployment_target:
                description: Change target for run
                required: true
                default: 
                type: choice
                options:
                    - first
                    - second

jobs: 
    test:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with: 
                python-version: "3.11"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: Install dependencies
              run: pip install -r requirments.txt
            - name: first
              if: "github.event.inputs.deployment_target == 'first'"
              run: pytest -s -v tests/test_button.py::test_is_button_exists_simple
            - name: second
              if: "github.event.inputs.deployment_target == 'second'"
              run: pytest -s -v tests/test_button.py::test_is_button_exists_like_a_button
